### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_models#2]
Since we are just starting maybe its a good time to think about whether we want tests and how/what we want to test.

**Comment by albertz** [comment]
You mean whether at all (of course we do), or consistently for everything?

I would say we don't need to have a strict rule on what must be tested and what not. We can just decide individually as we go. I usually add tests on things which are easy to get wrong, or where I'm maybe changing sth, to make sure I don't break it.
