### ISSUE TITLE
Sequence masking True/False mapping doc conformer

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_models#30]
https://github.com/rwth-i6/i6_models/blob/d2c8a246ce1174e098de7aa2208e6e7a05eebdb7/i6_models/assemblies/conformer/conformer_v1.py#L55

I just realized, this is wrong or did we agree on something else and I forgot? Since the MHSA module inverts the mask

**Comment by kuacakuaca** [comment]
fixed by https://github.com/rwth-i6/i6_models/pull/46.
