### ISSUE TITLE
Top level imports only

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/i6_models#31]
I think we should change the way of importing for i6_models that we always import from the top level (`from i6_models import XYZ`) , and pass every relevant class/function through the init files. Otherwise we can never reorder/restructure later as the location becomes part of the API. 

Opinions please!

**Comment by albertz** [comment]
I disagree. I think it is good to have some structure and to not have just one big flat namespace.

It might make sense to draw a boundary somewhere. The convention is usually to put `_` as a prefix to the filename (module name) (or directory name, i.e. package name) when it is considered as private. However, I think most of what we have so far is fine to be part of the API, so currently there is no real need for that. But there might be at some later point.

I never was such a big fan of the division between `assemblies`, `parts`, `primitives`, `util`. I keep forgetting which is which. I don't like that e.g. the Conformer implementation is spread out via this. I don't really see that this structure really has much benefit. This is sth I would remove from the API, from the hierarchy structure. But the structure below is fine. Maybe `util` is also fine.

It is easy to leave aliases later in case we want to restructure.

**Comment by curufinwe** [comment]
We decided to leave it as is for now after some offline discussion.
