### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_models#9]
When trying to use the first Conformer today, @JackTemaki brought up that if we now treat `i6_models` as recipe folder, than the depth of 2 of `i6_models` folders is problematic. 
Should we change this now? After the current PRs are through? Do we not change it? Maybe @JackTemaki can give more details.

**Comment by Atticus1806** [comment]
Bumping on this one. I think we should come up with a decision asap, since the more we implement the more difficult moving files will be. I guess if no one replies I guess Nick and I will just take a decision.

**Comment by curufinwe** [comment]
i6_models currently has the "normal" python project structure. The idea is to have this as a "normal" python library. My recommendation thus would be to work around the issue, either by symlinking, adding to PYTHONPATH or installing via pip (once we have a setup.py defined). Having the code all in the top-level makes the code less standalone.
